# for full syntax documentation see:  https://lgtm.com/help/lgtm/lgtm.yml-configuration-file

extraction:
  cpp:
    prepare:
      packages:
        - g++-10
        - ccache
      script:
        - python3 -m pip install cmake
        - source ~/.profile
    configure:
      command:
        - mkdir build
        - cmake -S . -B build
    index:
      build_command: cmake --build -j2
